[package]
name = "go"
version = "0.1.0"
authors = ["Jeremy Fitzhardinge <jeremy@goop.org>"]
readme = "README.md"

[[bin]]
name = "sgfreader"

[dependencies]
nom = "1.2"
lazy_static = "0.1"

[profile.release]
debug = true
